name: yaml_test_suite_runner
description: A custom YAML test suite runner.
version: 0.0.2

publish_to: none

environment:
  sdk: ^3.10.1

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  path: ^1.9.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
